/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDemo */

#ifndef _Included_JNIDemo
#define _Included_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDemo
 * Method:    sum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_JNIDemo_sum
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     JNIDemo
 * Method:    link
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIDemo_link
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
