#! /bin/bash
     
old_suffix=$1
new_suffix=$2

if (($# == 0))
then
	echo "Not enough arguments" >&2
	exit 1
fi
if (($# > 2))
then
	echo "To many arguments" >&2
	exit 1
fi
     
for f in *.$old_suffix
do
	new_name=${f%.*}.$new_suffix
	if [[ -e $new_name ]]
	then
		echo "$new_name already exists" >&2
		exit 1
	fi
	mv $f $new_name
	if (( $? != 0 ))
	then
		echo "Something went wrong" >&2
		exit 1
	fi
	echo Rename $f to $new_name
done
